apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: staging
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: jaspershop-public
          servicePort: jaspershop-port