kind: Service
apiVersion: v1
metadata:
  namespace: staging
  name: jaspershop-public
  labels:
    app: jaspershop-api
spec:
  type: NodePort
  ports:
  - name: jaspershop-api
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: jaspershop-api
---
kind: Service
apiVersion: v1
metadata:
  namespace: staging
  name: jaspershop
  labels:
    app: jaspershop-api
spec:
  type: ClusterIP
  ports:
  - name: jaspershop-api
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: jaspershop-api
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-files-pv-claim
  labels:
    app: jaspershop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: jaspershop-api
  labels:
    app: jaspershop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jaspershop-api
  template:
    metadata:
      annotations:
        version: latest
      labels:
        app: jaspershop-api
    spec:
      containers:

      - name: jaspershop-nginx
        image: nginx:stable
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-conf-volume
            mountPath: /etc/nginx/conf.d
          - name: sock-volume
            mountPath: /usr/src/app/
          - name: static-files-persistent-storage
            mountPath: /usr/src/app/static/

      - name: jaspershop-api
        image: suiyang03/k8s-jenkins-django-jasper-shop_api:latest
        imagePullPolicy: Always
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: JasperShop.k8s_settings.local
        command: ["/bin/sh","-c"]
        args: ["uwsgi --ini uwsgi.ini && python manage.py collectstatic"]
        volumeMounts:
          - name: static-files-persistent-storage
            mountPath: /usr/src/app/static/
          - name: sock-volume
            mountPath: /usr/src/app/socket/
      
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf
            items:
            - key: jaspershop-nginx.conf
              path: jaspershop-nginx.conf
        - name: sock-volume
          emptyDir: {}
        - name: static-files-persistent-storage
          persistentVolumeClaim:
            claimName: static-files-pv-claim